### ISSUE TITLE
read.electrophoresis: Unrecognized XML format

### ISSUE THREAD

**Issue by tylmoss** [jwfoley/bioanalyzeR#15]
First, thank you for this R package... it is wonderful.

I had issues importing the tapestation data with the `read.electrophoresis()` function.  The `read.tapestation()` function worked fine, so I narrowed the issue down to the first character in the xml not being recognized.  The first character of the tapestation xml files on my system is simply `rawToChar(as.raw(239))` and not `rawToChar(as.raw(c(239,187,190)))`.  I'm wondering if the expected first characters could be arguments of `read.electrophoresis` to make the function easier to use on different systems.

I am running it on a PC with R version 3.6.3.

Thanks,
Tyler

**Comment by tylmoss** [comment]
My thought for how a simple fix would work:

```
read.electrophoresis <- function(
  ...,
  fit = "spline",
  mc.cores = if (.Platform$OS.type == "windows") 1 else detectCores(),
  BIOANALYZER.FIRST.CHAR = "<",
  TAPESTATION.FIRST.CHAR = rawToChar(as.raw(c(239, 187, 191))),   # I could change this on my system
  GZIP.FIRST.CHAR = rawToChar(as.raw(31))
){

}
```

**Comment by jwfoley** [comment]
Thanks for your feedback. It looks like the problem is that `readChar()` has inconsistent behavior from one OS to another: on my machine it actually reads the first three bytes because they are a special byte-order mark. But `useBytes = T` appears to force consistent behavior so it should work on both platforms.

Can you please install this test package and confirm it resolves the problem? If so, I'll add it to the next release.

[bioanalyzeR_0.4.4-test.tar.gz](https://github.com/jwfoley/bioanalyzeR/files/5404283/bioanalyzeR_0.4.4-test.tar.gz)

**Comment by tylmoss** [comment]
Thank you for the quick response.  Yes, the `read.electrophoresis` wrapper function works on my system now.

**Comment by jwfoley** [comment]
Great. Please install the latest release with the normal instructions to overwrite that temporary version.
