### ISSUE TITLE
sample.observations

### ISSUE THREAD

**Issue by paliocha** [jwfoley/bioanalyzeR#2]
Change `sample.observations` in the `plot.electropherogram()` function to `name` so it matches the column name in the data frame generated by `read.bioanalyzer()`.

**Comment by jwfoley** [comment]
Instead I've added a new variable, `category`, that contains the sample type (`"Ladder"` or `"Sample"`) for both Bioanalyzer and TapeStation data, and now `plot.electropherogram()` checks that instead.

Please note that this repo is a work in progress, so the functions are still very crude, and the math for the TapeStation molarity estimation is still unproven while the Bioanalyzer molarity math is known to be wrong (I've added a warning to that effect). But since people are apparently interested in this I'll try to find some time to work on it more.
