### ISSUE TITLE
keep getting an error but not sure why 

### ISSUE THREAD

**Issue by CamRFerg** [jwfoley/bioanalyzeR#26]
I've been attempting to import some data using the following code:

```
femtodata <- read.prosize(
  electropherogram.csv = '2022 05 31 14H 43M Electropherogram.csv',
  calibration.csv = '2022 05 31 14H 43M Size Calibration.csv',
  peaks.csv = '2022 05 31 14H 43M Peak Table.csv',
  smear.csv = '2022 05 31 14H 43M Smear Analysis Result.csv',
  quality.csv = '2022 05 31 14H 43M Quality Table.csv',
  method = "hyman"
)
```
However, when I do this I get the following error:

> Error in read.prosize.peaks(peaks.csv) : 
>   missing or duplicated size column

I'm not sure what is causing this as the peak table csv contains the column and it is not duplicated? Any help you could provided would be appreciated.
[femto.zip](https://github.com/jwfoley/bioanalyzeR/files/8814483/femto.zip)

**Comment by jwfoley** [comment]
In the latest [release v0.10.0](https://github.com/jwfoley/bioanalyzeR/releases/tag/v0.10.0) I added a test to verify which peak table format you exported and let you know if it's wrong (should have done that originally - sorry!). I'll assume that's what the problem was here and close this issue, but feel free to reopen it if that hasn't solved your problem.
