### ISSUE TITLE
Tapestation Traces Not Loading Correctly

### ISSUE THREAD

**Issue by treodeo** [jwfoley/bioanalyzeR#27]
Hello!,

You're package has been greatly useful for comparing electropherograms across experiments! For one Tapestation file (CSV/XML), the traces are not loading correctly. Seems like the shape is reversed and squished along bp axis. I've re-exported the files and double-checked the settings but I can't seem to fix the problem. 

Are you able to take a look at this?

BioanalyzeR results:
![image](https://user-images.githubusercontent.com/6070112/191806914-35a1491b-ebd0-47a3-80b7-4dc57c38db7e.png)
Tapestation comparison:
![LT16_Comparison](https://user-images.githubusercontent.com/6070112/191806995-f7a91623-a4a3-4bc6-9b5b-6966ba5cf88c.png)

Associated files:
[TapestationExport.zip](https://github.com/jwfoley/bioanalyzeR/files/9627885/TapestationExport.zip)

**Comment by jwfoley** [comment]
Thanks for attaching the data. This isn't a bug, just the consequence of [different axis variables](https://stanford.edu/~jwfoley/bioanalyzeR.html#changing-the-axis-variables). You can recapitulate the TapeStation software's plot of the raw data with `rawplot.electrophoresis()`:

    > testdata <- read.electrophoresis("TapestationExport/LT16_cDNA_ReducingRNAInput - 2022-09-20 - 10-58-08-HSD5000.xml")
    > rawplot.electrophoresis(testdata, facets = NULL, region.fill = NA)

![rawplot](https://user-images.githubusercontent.com/12862657/192004771-749d342b-7b29-4c0e-af8e-109341e3ae7a.png)

When you change the x-axis from observed migration distance to a linear scale of molecule lengths calibrated by the ladder ([similar but not identical to a log scale](https://stanford.edu/~jwfoley/bioanalyzeR.html#stdcrv.mobility)), it narrows features on the left side of the graph and widens features on the right side:

    > qplot.electrophoresis(testdata, x = "length", y = "fluorescence", facets = NULL, title = "Fluorescence vs. length")

![fluor_vs_length](https://user-images.githubusercontent.com/12862657/192004818-9898cd7a-b1d4-4b43-bbcf-5c56b18b678c.png)

Things change a lot when you rescale the y-axis from fluorescence to concentration, because fluorescence is effectively measured per unit of migration distance (so the narrow features on the right of the original graph were mashed together and piled up higher while the wide features on the left were spread thin) while concentration is calculated per unit of molecule length in linear space:

    > qplot.electrophoresis(testdata, x = "length", y = "concentration", facets = NULL, title = "Concentration vs. length")

![conc_vs_length](https://user-images.githubusercontent.com/12862657/192004829-ee8e6432-1dde-4787-8131-dfa87c3001de.png)

And they change a lot again when you rescale from concentration to molarity (so much that I had to clip off the left end to see a reasonable scale), because concentration is molarity times length, so if you had two molecules of 100 bp and 500 bp that were exactly the same molarity, the concentration of the 500 bp molecule would be 5 times as great: 

    > qplot.electrophoresis(testdata, x = "length", y = "molarity", facets = NULL, title = "Molarity vs. length", xlim = c(120, NA))

![molar_vs_length](https://user-images.githubusercontent.com/12862657/192004856-8c1dd125-8ac6-4584-b1e8-cc25fbf2aefb.png)

In my experience, molarity vs. a linear length axis is the intuitive graph for most experiments, because it's really just a histogram of molecule frequency vs. molecule length, so that's the default for `qplot.electrophoresis()`. However, it looks very different from the raw data of fluorescence vs. mobility. I believe the raw data plots are therefore highly misleading and cause a lot of people to make a lot of bad decisions about their lab protocols, and someday I plan to write a vignette explaining this, but if you prefer the familiarity of the raw data anyway there's always `rawplot.electrophoresis()`.

Does that help?
