### ISSUE TITLE
Can't handle TS images with more than one ladder

### ISSUE THREAD

**Issue by natliang** [jwfoley/bioanalyzeR#3]
Thanks for the scripts, they're very helpful.

Is it possible to have the TS script be ok with the presence of multiple ladder lanes?
Every 15 samples, the TS will add a new ladder lane which ends up in the picture and xml. 
I guess you could either have it ignore the other ladders or just use each ladder for every set of 15 samples.
![example](https://user-images.githubusercontent.com/45465705/49470329-bc101500-f7d7-11e8-8944-464b24df4050.png)

**Comment by jwfoley** [comment]
I haven't seen this behavior before; which TapeStation version are you using (2200 or 4200)? Is this the "Electronic Ladder" or did you add an actual ladder sample for each tape? If it's the Electronic Ladder then it probably doesn't make a difference, but otherwise maybe it would be more accurate to calibrate separately for each tape. That would be a lot easier if there's something useful in the metadata.

Could you also upload the XML, or the original data file? You can anonymize all the samples if you're concerned about privacy.

**Comment by natliang** [comment]
We used the TS 4200. We loaded one actual ladder sample and I believe the machine took from that sample multiple times. I've uploaded the xml, saved as txt because of Github. 
[ts4200example.txt](https://github.com/jwfoley/bioanalyzeR/files/2646327/ts4200example.txt)

**Comment by jwfoley** [comment]
I pushed some commits into the `devel` branch that should resolve this. Now `read.tapestation` automatically detects whether the run contains one ladder per ScreenTape, and if so it uses each ladder to calibrate the samples in the same tape. Does that solve your problem?

**Comment by jwfoley** [comment]
marking as resolved since this seems fixed in `master` now
