### ISSUE TITLE
Genomic DNA TapeStation Analysis

### ISSUE THREAD

**Issue by jvanbelzen** [jwfoley/bioanalyzeR#31]
I'm trying plot data from a Genomic DNA Assay from a TapeStation.  Within he Agilent software, the peak maxima is calculated as 54,234 bp.  This is outside of the sizing range, but the Agilent software plots the sample as expected.  When trying to analyze this dataset with bioanalyzeR I get a graph with maxima elsewhere.  Is this plotting correctly?  TYIA

```
BY4741_gDNA <- read.electrophoresis("~/Desktop/TapeStation/2023-03-09 - BY4741 and JVY141 gDNA-gDNA/2023-03-09 - BY4741 and JVY141 gDNA-gDNA.xml")
BY4741_gDNA_BY <- subset(BY4741_gDNA, sample.name == "BY4741 gDNA Purified")
qplot.electrophoresis(BY4741_gDNA_BY,
                      show.peaks = "none",
                      facets = NULL,
                      y = "concentration",
                      title = "TapeStation gDNA")
```

![Screenshot 2023-06-23 at 1 59 34 PM](https://github.com/jwfoley/bioanalyzeR/assets/52330943/5df2cae6-a013-47f0-894a-009669d0d49f)
![Rplot](https://github.com/jwfoley/bioanalyzeR/assets/52330943/00cd30f9-a3e0-42a2-9746-9ce7a5687126)

**Comment by jwfoley** [comment]
Sorry for the slow reply. Does

    read.electrophoresis("~/Desktop/TapeStation/2023-03-09 - BY4741 and JVY141 gDNA-gDNA/2023-03-09 - BY4741 and JVY141 gDNA-gDNA.xml", extrapolate = TRUE)

do what you want? By default the algorithm that estimates molecule length from migration distance doesn't extrapolate outside of the ladder range, but if you're comfortable with guesses outside that range you can let it try. (If you want accurate results in that range, you'd need pulsed-field electrophoresis instead, so no interpretation of these data will be accurate.)

**Comment by jwfoley** [comment]
Also if you want a direct comparison with the Agilent graph, you can try `rawplot.electrophoresis` to avoid using length and concentration as the axes, though this usually isn't useful in the real world.

**Comment by jvanbelzen** [comment]
Sorry it took me so long to respond!

The following didn't appear to extend the x-axis: it still ends at 50,000 and generates the same plot as above.  I essentially just want to extend the the x-axis to ~75,000 bp. This will make it clear that the sample decreases in concentration around 60,000 bp.

```
qplot.electrophoresis(BY4741_gDNA_BY,
                      show.peaks = "none",
                      facets = NULL,
                      y = "concentration",
                      title = "TapeStation gDNA",
                      extrapolate = TRUE)
```

The following generates a plot similar to the default TapesStation plot
```
rawplot.electrophoresis(BY4741_gDNA_BY,
                      include.markers = TRUE,
                      facets = NULL,
                      title = "TapeStation gDNA",
                      extrapolate = FALSE)
```



![Plot2](https://github.com/jwfoley/bioanalyzeR/assets/52330943/b8d261c5-2e22-436f-8034-e4c470e5589a)

**Comment by jwfoley** [comment]
Does the option `include.markers = TRUE` do what you want? It is disabled by default because even length estimates, let alone concentrations, extrapolated outside of the marker/ladder range are highly suspect. This is true of Agilent's software as much as mine. Again I should emphasize that the numbers at the right end of this graph are qualitative at best, basically just vibes, when you're not using pulsed-field gel electrophoresis. I wouldn't read much into the data there and I would look for a pulsed-field setup (Agilent sells the Femto Pulse, and bioanalyzeR supports it, but it's hard to find one) if these results really matter to your work.

**Comment by jvanbelzen** [comment]
`include.markers = TRUE` plots a vertical line at x=0 and a horizontal line at y=0.  Not sure what's going on there.

I'm able to extend the x-axis using `xlim = c(0, 70000)` but no data is plotted past the peak concentration.  However, the original file must have data that extends beyond this, as TapeStation Image in my first post shows the peak maxima at ~54000 bp, after which it decreases to baseline.  So it should eventually come down in concentration as molecular weight increases.  Looks like the data past ~54,000 is being excluded for some reason.

`qplot.electrophoresis(BY4741_gDNA_BY,
                      show.peaks = "none",
                      facets = NULL,
                      y = "concentration",
                      title = "TapeStation gDNA",
                      xlim = c(0, 70000))`

No big deal if this isn't the intended purpose of your package.  I can use `rawplot.electrophoresis()` to get plots that will work for me.

![Plot](https://github.com/jwfoley/bioanalyzeR/assets/52330943/65af0921-e165-4f58-a817-0a94d8f19492)

**Comment by jwfoley** [comment]
The spike near *x = 0* is probably the 100 bp marker peak (use `show.peaks = "m"` to fill it), which needs a very high concentration to compensate for its short length and generate detectable fluorescence. You might want to cut off *x* a little later, e.g. `xlim = c(200, 70000)`, to miss it.

But did you give the argument `extrapolate = TRUE` to `read.electrophoresis()`? That's where it needs to be applied, but I see in your previous message it was inside `qplot.electrophoresis()` instead, where it isn't recognized. Otherwise the data will stop at 48,500 bp, the last ladder peak.

If this doesn't resolve the problem please post your data files (XML and CSV) so I can take a look myself.

**Comment by jvanbelzen** [comment]
Doh!  I was trying to put `extrapolate = TRUE` as an argument in `qplot.electrophoresis()`.  This does work when properly put as an argument within `read.electrophoresis()`.  Thank you !
```
qplot.electrophoresis(BY4741_gDNA_BY,
                      show.peaks = "none",
                      facets = NULL,
                      y = "concentration",
                      title = "TapeStation gDNA",
                      xlim = c(0, 70000))
```
![plot](https://github.com/jwfoley/bioanalyzeR/assets/52330943/9dfd3f57-cad8-49ca-bcf2-deb53f9afc34)
